"""Generate docs/normalization-report.md from the shared fixtures.

    python -m doggfather.tools.normalization_report fixtures.json > docs/normalization-report.md

Everything in the report is recomputed from scratch: the fixture scorecards
(equal weights, the fixture event's rubric), the four methods, the rank
movements, the judge calibration, a lambda sensitivity sweep, and the
planted-bias simulation that JUDGING.md cites as the proof.
"""

from __future__ import annotations

import argparse
import random
import statistics
import sys
import tempfile
from collections import defaultdict
from pathlib import Path

from doggfather import db
from doggfather.config import load_settings
from doggfather.seed import seed
from doggfather.services import normalization
from doggfather.services.events import get_event
from doggfather.services.normalization import METHOD_LABELS, METHODS, Observation, spearman
from doggfather.services.results import compute_table, observations

SEEDS = 40


def simulate(seed_value: int, n_projects=40, n_judges=24, n_tracks=6, k=3, bias_sd=0.7, noise_sd=0.35):
    rng = random.Random(seed_value)
    truth = {f"p{i:02d}": rng.gauss(3.0, 0.6) for i in range(n_projects)}
    track = {p: i % n_tracks for i, p in enumerate(truth)}
    judges = [f"j{i:02d}" for i in range(n_judges)]
    cover = {j: {i % n_tracks, rng.randrange(n_tracks)} for i, j in enumerate(judges)}
    bias = {j: rng.gauss(0, bias_sd) for j in judges}
    load = dict.fromkeys(judges, 0)
    obs = []
    for p in truth:
        eligible = [j for j in judges if track[p] in cover[j]]
        rng.shuffle(eligible)
        for j in sorted(eligible, key=lambda name: load[name])[:k]:
            load[j] += 1
            obs.append(Observation(j, p, min(5.0, max(1.0, truth[p] + bias[j] + rng.gauss(0, noise_sd)))))
    return truth, obs


def top(scores: dict[str, float], n: int = 10) -> set[str]:
    return set(sorted(scores, key=lambda p: -scores[p])[:n])


def build(fixtures_path: Path) -> str:
    import json

    fixtures = json.loads(fixtures_path.read_text(encoding="utf-8"))
    with tempfile.TemporaryDirectory() as tmp:
        settings = load_settings(data_dir=Path(tmp), secret_key="report", demo=False, webhook_worker=False)
        conn = db.connect(settings.database_path)
        db.migrate(conn)
        seed(conn, settings, fixtures)
        event = get_event(conn, fixtures["event"]["id"])
        table = compute_table(conn, event, "bias")
        obs = observations(conn, event.id)
        conn.close()

    out: list[str] = []
    w = out.append
    by_judge: dict[str, list[float]] = defaultdict(list)
    per_project: dict[str, int] = defaultdict(int)
    for o in obs:
        by_judge[o.judge].append(o.score)
        per_project[o.project] += 1

    w("# Normalization report: DOGFOOD fixtures\n")
    w("Generated by `python -m doggfather.tools.normalization_report fixtures.json`. Every number below is")
    w("recomputed from `fixtures.json`; nothing is hand-edited. The method is described and defended in")
    w("[JUDGING.md](../JUDGING.md).\n")
    w("## The data\n")
    w(f"- {len(obs)} scorecards from {len(by_judge)} judges on {len(per_project)} projects "
      f"(the rubric's three criteria, equal weights, 1–5 scale)")
    counts = defaultdict(int)
    for n in per_project.values():
        counts[n] += 1
    w("- reviews per project: " + ", ".join(f"{k} reviews × {v}" for k, v in sorted(counts.items())))
    loads = sorted(len(v) for v in by_judge.values())
    w(f"- scorecards per judge: min {loads[0]}, median {statistics.median(loads):g}, max {loads[-1]}")
    w(f"- judge graph: {len(table.components)} connected component(s), so every judge's bias is estimated "
      "against every other's through shared projects")
    flat = [j for j in table.judges if j["flat"]]
    w(f"- flat scorers (every scorecard identical): " + (", ".join(f"{j['name']} ({j['id']}, {j['n']}×{j['mean']:.2f})" for j in flat) or "none"))
    thin = [j for j in table.judges if j["n"] == 1]
    w(f"- single-review judges: " + (", ".join(f"{j['name']} ({j['id']})" for j in thin) or "none") + "\n")

    w("## Agreement with the raw ranking\n")
    w("Spearman rank correlation of each method's ranking with the raw-mean ranking. Values below 1 are")
    w("the corrections.\n")
    w("| Method | ρ vs raw |")
    w("|---|---|")
    for m, rho in table.info["agreement"].items():
        w(f"| {METHOD_LABELS[m]} | {rho:.3f} |")
    w("")

    w("## Rank movements (default method: judge-bias model)\n")
    w("Positive movement = climbed relative to the raw mean. Projects are listed by normalized rank.\n")
    w("| Rank | Project | Track | Reviews | Raw (rank) | Z-shrunk (rank) | Bias model (rank) | BT θ (rank) | Move |")
    w("|---:|---|---|---:|---|---|---|---|---:|")
    for r in table.rows:
        move = f"+{r['movement']}" if r["movement"] > 0 else str(r["movement"])
        w(f"| {r['rank']} | {r['title']} ({r['id']}) | {r['track_name'] or '-'} | {r['reviews']} | "
          f"{r['raw']:.3f} ({r['raw_rank']}) | {r['zscore']:.3f} ({r['zscore_rank']}) | "
          f"{r['bias']:.3f} ({r['bias_rank']}) | {r['pairwise']:+.3f} ({r['pairwise_rank']}) | {move} |")
    w("")
    biggest = sorted(table.rows, key=lambda r: -abs(r["movement"]))[:5]
    w("Largest movements: " + "; ".join(f"{r['title']} {'+' if r['movement'] > 0 else ''}{r['movement']}" for r in biggest) + ".\n")

    w("## Judge calibration\n")
    w("`bias` is the judge effect the model subtracts, in rubric points (+ generous, − harsh), after ridge")
    w("shrinkage toward 0 with λ = 2.\n")
    w("| Judge | Scorecards | Mean | SD | Bias | Flags |")
    w("|---|---:|---:|---:|---:|---|")
    for j in sorted(table.judges, key=lambda j: j["bias"]):
        flags = ", ".join(f for f, on in (("flat scorer", j["flat"]), ("few reviews", j["thin"])) if on)
        w(f"| {j['name']} ({j['id']}) | {j['n']} | {j['mean']:.2f} | {j['sd']:.2f} | {j['bias']:+.3f} | {flags} |")
    w("")

    w("## Sensitivity to λ\n")
    w("How much the top 10 depends on the shrinkage strength. `overlap` is the share of the λ = 2 top 10 that")
    w("is still top 10.\n")
    reference = normalization.judge_bias_model(obs, lam=2.0).scores
    w("| λ | ρ vs λ=2 | top-10 overlap |")
    w("|---:|---:|---:|")
    for lam in (0.25, 0.5, 1.0, 2.0, 5.0, 10.0, 50.0):
        scores = normalization.judge_bias_model(obs, lam=lam).scores
        w(f"| {lam:g} | {spearman(scores, reference):.3f} | {len(top(scores) & top(reference)) / 10:.0%} |")
    w("\nAs λ grows the model approaches the raw mean (no bias correction). Small λ trusts every judge's")
    w("estimated bias fully, including one-review judges. The ranking is stable across a wide middle band.\n")

    w(f"## Proof by simulation ({SEEDS} random events)\n")
    w("Each simulated event has 40 projects with a hidden true quality ~ N(3, 0.6), 24 judges with a hidden")
    w("bias ~ N(0, 0.7) and noise ~ N(0, 0.35), 6 tracks, and 3 track-limited reviews per project, with")
    w("scores clamped to 1–5 like a real rubric. We ask how well each method recovers the *true* ranking.\n")
    rho: dict[str, list[float]] = {m: [] for m in METHODS}
    for s in range(SEEDS):
        truth, sim = simulate(s)
        for m in METHODS:
            rho[m].append(spearman(normalization.compute(m, sim).scores, truth))
    w("| Method | mean ρ vs truth | worst seed | beats raw |")
    w("|---|---:|---:|---:|")
    for m in METHODS:
        wins = sum(a > b for a, b in zip(rho[m], rho["raw"])) if m != "raw" else 0
        w(f"| {METHOD_LABELS[m]} | {statistics.fmean(rho[m]):.3f} | {min(rho[m]):.3f} | "
          f"{'-' if m == 'raw' else f'{wins}/{SEEDS}'} |")
    w("\nThe test suite asserts the same property on 20 seeds (tests/test_normalization.py).")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("fixtures", type=Path, nargs="?", default=Path("fixtures.json"))
    args = parser.parse_args(argv)
    sys.stdout.write(build(args.fixtures))
    return 0


if __name__ == "__main__":
    sys.exit(main())
